---
settings:
  name: E-Series
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti e-Series
    url: "/index.html"
  - title: Note di rilascio
    url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Scopri i tuoi sistemi e-Series
      url: "/task-discover-e-series.html"
  - title: Gestire i cluster e-Series
    entries:
    - title: Visualizza i tuoi sistemi e-Series
      url: "/task-view-e-series.html"
    - title: Rimuovere e-Series
      url: "/task-remove-e-series.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Scopri i tuoi sistemi e-Series
      url: "/task-discover-e-series.html"
  - title: Gestire i sistemi e-Series
    links:
    - title: Visualizza i tuoi sistemi e-Series
      url: "/task-view-e-series.html"
    - title: Rimuovere e-Series
      url: "/task-remove-e-series.html"
  - title: Link correlati
    links:
    - title: Documentazione e-Series per la gestione al di fuori di BlueXP
      url: https://docs.netapp.com/us-en/e-series-family/
  - title: Blog e community
    links:
    - title: Community NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://cloud.netapp.com/blog
    - title: Webinar sul cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: Tutta la documentazione BlueXP
